name: CI

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - closed

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install Vite+
        uses: voidzero-dev/setup-vp@v1
        with:
          node-version: "24"
          cache: true
      - name: Install Dependencies
        run: vp install
      - name: Run Check
        run: vp run check

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install Vite+
        uses: voidzero-dev/setup-vp@v1
        with:
          node-version: "24"
          cache: true
      - name: Install dependencies
        run: vp install
      - name: Run Tests
        run: vp run test

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install Vite+
        uses: voidzero-dev/setup-vp@v1
        with:
          node-version: "24"
          cache: true
      - name: Install Dependencies
        run: vp install
      - name: Run Build
        run: vp run build
